# Generated by Django 3.1.1 on 2021-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_typecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='document',
            field=models.FileField(default='', null=True, upload_to='uploads/contact'),
        ),
    ]
