# Generated by Django 3.1.1 on 2021-01-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210111_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='vgender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non binary')], default='M', max_length=15),
        ),
    ]
