# Generated by Django 3.1.1 on 2021-01-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_contact_vgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comment.typecontact'),
        ),
    ]
