# Generated by Django 3.1.1 on 2021-01-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20210111_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.typecontact'),
        ),
    ]
