# Generated by Django 3.1.1 on 2021-01-11 06:20

from django.db import migrations, models

def insert_data(apps, schema_editor):
    type_contact = apps.get_model('comment', 'TypeContact')
    contact_business = type_contact(name = "Business")
    contact_business.save()
    contact_government = type_contact(name = "Government")
    contact_government.save()
    contact_university = type_contact(name = "University")
    contact_university.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20210111_0617'),
    ]
     
    operations = [
        migrations.AlterField(
            model_name='typecontact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(insert_data),
    ]
