# Generated by Django 3.1.1 on 2020-09-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
